"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SALT_OR_ROUNDS = exports.USER_REPOSITORY = exports.TEST_ANSWER_REPOSITORY = exports.TEST_ATTEMPT_REPOSITORY = exports.TEST_ASSIGNMENT_REPOSITORY = exports.TEST_QUESTION_REPOSITORY = exports.TEST_CATEGORY_REPOSITORY = exports.TEST_REPOSITORY = exports.PRODUCTION = exports.STAGING = exports.TEST = exports.DEVELOPMENT = exports.SEQUELIZE = void 0;
exports.SEQUELIZE = 'SEQUELIZE';
exports.DEVELOPMENT = 'development';
exports.TEST = 'test';
exports.STAGING = 'staging';
exports.PRODUCTION = 'production';
exports.TEST_REPOSITORY = 'TEST_REPOSITORY';
exports.TEST_CATEGORY_REPOSITORY = 'TEST_CATEGORY_REPOSITORY';
exports.TEST_QUESTION_REPOSITORY = 'TEST_QUESTION_REPOSITORY';
exports.TEST_ASSIGNMENT_REPOSITORY = 'TEST_ASSIGNMENT_REPOSITORY';
exports.TEST_ATTEMPT_REPOSITORY = 'TEST_ATTEMPT_REPOSITORY';
exports.TEST_ANSWER_REPOSITORY = 'TEST_ANSWER_REPOSITORY';
exports.USER_REPOSITORY = 'USER_REPOSITORY';
exports.SALT_OR_ROUNDS = 10;
//# sourceMappingURL=index.js.map